### ISSUE TITLE
Dockerize System

### ISSUE THREAD

**Issue by goobta** [WPI-MMR/learning_experiments#4]
Grrr I **hate** GPUs! Stable baselines is running tf 1.15, while tf agents is tf2, AND EVERYTHING REQUIRES DIFFERENT CUDA/CUDNN VERSIONS GAHHHHHHH!!!!!!!

I've reinstalled my host OS drivers 4 times now and I still can't get the GPU working. Stick the damn project in a Docker container, run it via `nvidia-docker` and goddamn it, call it a day.

**Comment by mahajanrevant** [comment]
Aite
